baseURL = "https://toughpixels.com"
languageCode = "en-us"
title = "Tough Pixels Tips"
theme = "base"
publishDir = "docs"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
    description = "Common sense web development. We combine modern tools with enduring standards to help clients own their content."
    images = ["toughpixels.png"]
    author = "Tough Pixels"
    title = "Tough Pixels"
    imageSizes = "1280 640 320"
    imageFormats = "webp jpeg"
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
