baseURL = "https://toughpixels.com"
languageCode = "en-us"
title = "Tough Pixels Tips"
theme = "tips"
publishDir = "docs"
[params]
    description = "Simple explanations for coding problems."
    images = ["images/logo.jpg"]
    author = "Tough Pixels"
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true