backend:
  name: git-gateway
  branch: main
media_folder: static/images
public_folder: /images
collections:
  - name: 'tips'
    label: 'Tips'
    folder: 'content/tips/'
    path: '{{slug}}/_index'
    media_folder: ''
    public_folder: ''
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Header Image", name: header, widget: "image", required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Date", name: "date", widget: "datetime"}